name: video_quiz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_route: ^8.0.0
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  bloc_presentation: ^1.0.0
  chewie: ^1.8.1
  collection: ^1.18.0
  dartx: ^1.2.0
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.3
  file_picker: ^8.0.3
  file_saver: ^0.2.12
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.7.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  provider: ^6.1.2
  uuid: ^4.4.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
